language: cpp

matrix:
  include:
    - os: osx
      compiler: clang

before_script:
    - brew update
    - cp utilities/installation/brew/gazebo-yarp-plugins.rb `brew --prefix`/Library/Formula
    - brew install --verbose gazebo-yarp-plugins

script: 
    - echo "ok"
notifications:
  email:
    - pegua1@gmail.com
